name: QuickBook CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # FRONTEND
      - name: Install Frontend
        run: npm install

      - name: Build Frontend
        run: npm run build

      # BACKEND (safe check)
      - name: Install Backend
        run: |
          if [ -f backend/package.json ]; then
            cd backend
            npm install
          else
            echo "No backend package.json found"
          fi